server.port=8081
spring.application.name=imitator-collector
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/
springdoc.show-actuator=false

spring.threads.virtual.enabled=true

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never

collector.mongo.connect-timeout-seconds=10
collector.mongo.read-timeout-seconds=60
collector.mongo.server-selection-timeout-seconds=10

collector.sampling.sample-size=50

collector.internal-databases[0]=admin
collector.internal-databases[1]=local
collector.internal-databases[2]=config
collector.cosmosdb.phantom-collections[0]=lection
collector.cosmosdb.system-indexes[0]=DocumentDBDefaultIndex_1
#collector.cosmosdb.system-indexes[1]=DocumentDBDefaultIndex_2dsphere

logging.level.io.diegorocha.imitator.collector=DEBUG
logging.level.org.mongodb.driver=WARN
logging.level.org.springframework=WARN
logging.level.org.springframework.boot.web.embedded=INFO

logging.file.name=logs/app.log
#The filename pattern used to create log archives.
logging.logback.rollingpolicy.file-name-pattern=logs/%d{yyyy-MM, aux}/app.%d{yyyy-MM-dd}.%i.log
#The maximum size of log file before it is archived.
logging.logback.rollingpolicy.max-file-size=100MB
#The maximum amount of size log archives can take before being deleted.
logging.logback.rollingpolicy.total-size-cap=10GB
#The maximum number of archive log files to keep (defaults to 7).
logging.logback.rollingpolicy.max-history=10